name: hello_captain_user
description: "Service for Nepalis"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

#App Store: Use below commands, then archive in XCode
#flutter clean
#flutter pub get
#flutter build ios --release

version: 1.6.26+40

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_carousel_widget: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.5
  intl: ^0.20.1
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  animations: ^2.0.11
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.0.0
  skeletonizer: ^2.0.1
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  flutter_staggered_grid_view: ^0.7.0
  mapbox_maps_flutter: ^2.6.1
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  image_picker: ^1.1.2
  firebase_database: ^11.3.4
  flutter_html: ^3.0.0
  flutter_native_contact_picker: ^0.0.10
  simple_shadow: ^0.3.1
  khalti_checkout_flutter: ^1.0.0-dev.8
  cloud_firestore: ^5.6.7
  lottie: ^3.3.1
  photo_view: ^0.15.0
  firebase_storage: ^12.4.5
  share_plus: ^11.0.0
  flutter_rating_bar: ^4.0.1
  flutter_rating: ^2.0.2
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/category/
    - assets/icons/maps-icon/
    - assets/images/
    - assets/images/welcome/
    - assets/images/payment/
    - assets/animations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
